version: '3.7'

services:
  client-testnet:
    container_name: client-testnet
    image: gojoychain/go-geth:v1.8.23a
    restart: always
    env_file: .env
    ports:
      - 40303:30303
      - 40303:30303/udp
    volumes:
      - /home/ubuntu/.joy/testnet:/root/.ethereum
      - ./genesis.json:/root/.joy/genesis.json
      - ./static-nodes.json:/root/.joy/static-nodes.json
      - ./run.sh:/root/.joy/run.sh
    entrypoint: /root/.joy/run.sh
    logging:
      driver: json-file
      options:
        max-size: "400m"
        max-file: "10"
